config/routes.rb
Rails.application.routes.draw do



  get 'dashboard/index'
  get 'home/subscribe'
  get 'invoices/invo1'

  resources :clients
  resources :addresses
  resources :phones
  resources :emails

  resources :companies

  resources :invoices

  resources :items
  resources :services

  resources :users, only: [:new, :create] do
    collection do
      get   :edit
      patch :update
    end
  end

  resources :sessions, only: [:new, :create] do
    # this will create for us a route with DELETE http verb and /sessions
    # adding the on: :collection option will make it part of the routes for
    # sessions which means it won't prepend the routes with /sessions/:session_id
    delete :destroy, on: :collection
  end



  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    user ||= User.new


    if user.admin?
       can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
  # belongs_to :company

  validates :address1, presence: true
  validates :city,     presence: true
  validates :state,    presence: true
  validates :zip,      presence: true

  def display
    "#{address1} #{city} #{state} #{country} #{zip}"
  end

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :company

  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :phones,    as: :phonable, dependent: :destroy
  has_many :emails,    as: :emailable, dependent: :destroy

  accepts_nested_attributes_for :addresses
end

app/models/company.rb
class Company < ActiveRecord::Base


  # belongs_to :user
  has_one :user

  has_many :items, dependent: :destroy
  has_many :services, dependent: :destroy
  has_many :clients, dependent: :nullify
  has_many :invoices, dependent: :destroy

  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :phones,    as: :phonable, dependent: :destroy
  has_many :emails,    as: :emailable, dependent: :destroy

  accepts_nested_attributes_for :addresses, reject_if: :all_blank
  accepts_nested_attributes_for :phones, reject_if: :all_blank
  accepts_nested_attributes_for :emails, reject_if: :all_blank

  validates :name,    presence: true
  validates :addresses, presence: true



end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :emailable, polymorphic: true
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :invoiced_items, dependent: :destroy
  has_many :items, through: :invoiced_items

  has_many :invoiced_services, dependent: :destroy
  has_many :services, through: :invoiced_services

  belongs_to :company


  #scope :latest_first, lambda { order ("date DESC") }
  def self.latest_first
    order("created_at DESC")
  end
end

app/models/invoiced_item.rb
class InvoicedItem < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :item
end

app/models/item.rb
class Item < ActiveRecord::Base

  has_many :invoiced_items, dependent: :destroy
  has_many :invoices, through: :invoiced_items

  belongs_to :company



end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :phonable, polymorphic: true
end

app/models/service.rb
class Service < ActiveRecord::Base

  has_many :invoiced_services, dependent: :destroy
  has_many :invoices, through: :invoiced_services

  belongs_to :company

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  # has_one :company
  belongs_to :company


  validates :email, presence: {message: "must be present"}, uniqueness: true,
             format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i



end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to image_tag("Drawing13.png"), root_path, class: "navbar-brand topnav" %>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Create Invoice", new_invoice_path %></li>
        <li><%= link_to "Create Product", new_item_path %></li>
        <li><%= link_to "Create Service", new_service_path %></li>
        <li><%= link_to "Create Client", new_client_path %></li>
        <li><%= link_to "Dashboard", dashboard_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.first_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <%if current_user.company %>
              <li><%= link_to "Edit Your Company", edit_company_path(current_user.company) %></li>
            <% else %>
              <li><%= link_to "Create Company", new_company_path %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Edit Account Details", edit_users_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
            </ul>
            <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Sign in", new_session_path %></li>
          <% end %>
        </li>
      </ul>
  </div>
</nav>

app/views/layouts/_navdashboard.html.erb
<nav class="navbar navbar-inverse topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to image_tag("Drawing13.png"), root_path, class: "navbar-brand topnav" %>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Create Invoice", new_invoice_path %></li>
        <li><%= link_to "Create Product", new_item_path %></li>
        <!-- <li><%#= link_to "Create Service", new_service_path %></li> -->
        <li><%= link_to "Create Client", new_client_path %></li>
        <li><%= link_to "Dashboard", dashboard_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.first_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <%if current_user.company %>
              <li><%= link_to "Edit Your Company", edit_company_path(current_user.company) %></li>
            <% else %>
              <li><%= link_to "Create Company", new_company_path %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Edit Account Details", edit_users_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
            </ul>
            <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Sign in", new_session_path %></li>
          <% end %>
        </li>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceCore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/nav' %>
  <div class="rowr">
      <%= yield %>
  </div>

    <!-- <header>
        <div class="header-content">
              <%#= yield %>
            <div class="header-content-inner">
                <h1>Your Favorite Source of Free Invoicing</h1>
                <hr>
                <p>Start Invoicing...Let's get started</p>
                <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
            </div>
        </div>
    </header> -->


<!-- <div class="container">

  <%#= yield %>
</div> -->
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceCore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render '/layouts/nav' %>
  <header id="top" class="header">
        <div class="text-vertical-center">
          <div class="container">
            <%= yield %>
          </div>
        </div>
    </header>
</body>
</html>

app/views/layouts/note.html.erb
<nav class="navbar navbar-inverse topnav" role="navigation">
  <div class="container topnav">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to image_tag("Drawing3.png"), root_path, class: "navbar-brand topnav" %>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Create Invoice", new_invoice_path %></li>
        <li><%= link_to "Create Product", new_item_path %></li>
        <li><%= link_to "Create Service", new_service_path %></li>
        <li><%= link_to "Create Client", new_client_path %></li>
        <li><%= link_to "Dashboard", dashboard_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.first_name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <%if current_user.company %>
              <li><%= link_to "Edit Your Company", edit_company_path(current_user.id) %></li>
            <% else %>
              <li><%= link_to "Create Company", new_company_path %></li>
            <% end %>
            <li class="divider"></li>
            <li><%= link_to "Edit Account Details", edit_users_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
            </ul>
            <% else %>
            <li><%= link_to "Sign up", new_user_path %></li>
            <li><%= link_to "Sign in", new_session_path %></li>
          <% end %>
        </li>
      </ul>
  </div>
</nav>



<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">TallyForMe</a>
            </div>
            <ul class="nav navbar-nav">
              <li><%= link_to "Create Invoice", new_invoice_path %></li>
              <li><%= link_to "Create Product", new_item_path %></li>
              <li><%= link_to "Create Service", new_service_path %></li>
              <li><%= link_to "Create Client", new_client_path %></li>
              <li><%= link_to "Dashboard", dashboard_index_path %></li>
            </ul>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Portfolio</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                    <% if user_signed_in? %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.first_name %><span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <%if current_user.company %>
                          <li><%= link_to "Edit Your Company", edit_company_path(current_user.id) %></li>
                        <% else %>
                          <li><%= link_to "Create Company", new_company_path %></li>
                        <% end %>
                        <li class="divider"></li>
                        <li><%= link_to "Edit Account Details", edit_users_path %></li>
                        <li class="divider"></li>
                        <li><%= link_to "Sign out", sessions_path, method: :delete %></li>
                        </ul>
                        <% else %>
                        <li><%= link_to "Sign up", new_user_path %></li>
                        <li><%= link_to "Sign in", new_session_path %></li>
                      <% end %>
                    </li>
                </ul>
            </div>
        </div>
    </nav>